"""Native expectations are independent of the Studio parser and emitter."""

from __future__ import annotations

import base64
import hashlib
import json
import runpy
import xml.etree.ElementTree as ET
from dataclasses import FrozenInstanceError, replace
from pathlib import Path

import pytest

from gpo_studio.firewall_policy import (
    FIREWALL_KEY,
    FIREWALL_TOOL_GUID,
    FirewallPolicy,
    FirewallProfileSettings,
    FirewallRule,
    FirewallValidationError,
    UnknownFirewallToken,
    from_registry_records,
    to_registry_settings,
)
from gpo_studio.model import RegistrySetting
from gpo_studio.registry_pol import PolRecord, parse, serialize

ROOT = Path(__file__).resolve().parents[1]
FIXTURE = ROOT / "tests/fixtures/native-firewall-gpmc"


def native_bytes() -> bytes:
    return (FIXTURE / "Registry.pol").read_bytes()


def expected_policy() -> FirewallPolicy:
    # Written from the native capture, never generated by the codec under test.
    rules = (
        FirewallRule(
            "StudioFwProbe-01",
            "StudioFwProbe in tcp allow",
            protocol=6,
            profiles=("domain",),
            local_port="65001",
        ),
        FirewallRule(
            "StudioFwProbe-02",
            "StudioFwProbe out udp block range",
            direction="outbound",
            action="block",
            protocol=17,
            profiles=("domain", "private"),
            remote_port_range=(65002, 65003),
            remote_port=65010,
        ),
        FirewallRule("StudioFwProbe-03", "StudioFwProbe icmpv4 echo", protocol=1, icmp4="8:0"),
        FirewallRule("StudioFwProbe-04", "StudioFwProbe icmpv6 any", protocol=58),
        FirewallRule(
            "StudioFwProbe-05",
            "StudioFwProbe any protocol addresses",
            action="block",
            local_address="198.51.100.7",
            remote_addresses=("192.0.2.0/255.255.255.0", "2001:db8::/32"),
        ),
        FirewallRule(
            "StudioFwProbe-06",
            "StudioFwProbe program",
            direction="outbound",
            protocol=6,
            remote_port=443,
            program=r"%ProgramFiles%\StudioProbe\probe.exe",
        ),
        FirewallRule(
            "StudioFwProbe-07",
            "StudioFwProbe service",
            protocol=6,
            local_port="65004",
            service="GPOStudioProbe",
        ),
        FirewallRule(
            "StudioFwProbe-08",
            "StudioFwProbe rpc keyword",
            protocol=6,
            local_port="RPC",
            remote_addresses=("LocalSubnet",),
        ),
        FirewallRule(
            "StudioFwProbe-09", "StudioFwProbe rpc epmap", protocol=6, local_port="RPC-EPMap"
        ),
        FirewallRule(
            "StudioFwProbe-10",
            "StudioFwProbe disabled grouped",
            protocol=6,
            local_port="65005",
            enabled=False,
            description="synthetic probe rule",
            group="Studio Probe Group",
        ),
        FirewallRule(
            "StudioFwProbe-11",
            "StudioFwProbe edge and interface",
            protocol=17,
            local_port="65006",
            edge_traversal=True,
            interface_type="Lan",
        ),
        FirewallRule(
            "StudioFwProbe-12",
            "StudioFwProbe protocol number",
            direction="outbound",
            action="block",
            protocol=47,
        ),
        FirewallRule(
            "StudioFwProbe-13",
            "StudioFwProbe override block",
            protocol=6,
            action="bypass",
            local_port="65007",
            remote_machine="D:(A;;CC;;;WD)",
            security="Authenticate",
        ),
    )
    return FirewallPolicy(
        policy_version=545,
        domain=FirewallProfileSettings(
            enabled=True,
            default_inbound_action="block",
            default_outbound_action="allow",
            log_dropped_packets=True,
            log_successful_connections=False,
            log_file_size_kb=8192,
            log_file_path=r"%systemroot%\system32\LogFiles\Firewall\studio-domain.log",
        ),
        private=FirewallProfileSettings(
            enabled=True,
            default_inbound_action="block",
            disable_notifications=True,
            log_successful_connections=True,
        ),
        public=FirewallProfileSettings(),
        rules=rules,
    )


def test_native_parse_matches_every_typed_field() -> None:
    records = parse(native_bytes())
    assert len(records) == 25
    result = from_registry_records(records)
    assert result.unrecognised_records == ()
    assert len(result.policy.rules) == 13  # A parser returning nothing cannot pass.
    assert result.policy == expected_policy()
    assert result.policy.validate() == ()


def test_emit_independent_model_matches_native_record_bytes() -> None:
    emitted = to_registry_settings(expected_policy())
    native = parse(native_bytes())
    assert len(emitted) == len(native) == 25
    assert all(r.side == "computer" and r.hive == "HKLM" for r in emitted)
    # Compare raw native record slices, not just a parse/serialize tautology.
    # Native order is different; each one-record serialization supplies only
    # the header followed by that native record's exact UTF-16 wire bytes.
    by_identity = {(r.key, r.value_name): r for r in emitted}
    offset = 8
    native_chunks = []
    for record in native:
        chunk = serialize([by_identity[(record.key, record.value_name)]])[8:]
        assert native_bytes()[offset : offset + len(chunk)] == chunk
        native_chunks.append(chunk)
        offset += len(chunk)
    assert offset == len(native_bytes())
    assert b"PReg\x01\x00\x00\x00" + b"".join(native_chunks) == native_bytes()
    assert serialize(emitted) == serialize(native)
    assert serialize(emitted) != native_bytes()  # Documented record-order difference.
    assert parse(serialize(emitted)) == sorted(
        native, key=lambda r: (r.key.casefold(), r.value_name.casefold())
    )


def test_native_round_trip_and_setting_input() -> None:
    model = from_registry_records(parse(native_bytes())).policy
    settings = to_registry_settings(model)
    assert from_registry_records(settings).policy == expected_policy()
    assert from_registry_records(parse(serialize(settings))).policy == expected_policy()


def test_not_configured_is_absence_and_false_is_a_value() -> None:
    records = to_registry_settings(expected_policy())
    assert not any("PublicProfile" in r.key for r in records)
    assert not any(
        "PrivateProfile" in r.key and r.value_name == "DefaultOutboundAction" for r in records
    )
    assert any(r.value_name == "LogSuccessfulConnections" and r.value == 0 for r in records)
    assert from_registry_records([]).policy == FirewallPolicy()
    assert to_registry_settings(FirewallPolicy()) == []


def test_cidr_and_family_split_equal_native_wire() -> None:
    policy = expected_policy()
    rule = replace(policy.rules[4], remote_addresses=("2001:db8::/32", "192.0.2.0/24"))
    modified = replace(policy, rules=policy.rules[:4] + (rule,) + policy.rules[5:])
    assert serialize(to_registry_settings(modified)) == serialize(parse(native_bytes()))


def test_unknown_tokens_preserved_in_order_and_refused_on_write() -> None:
    records = parse(native_bytes())
    rule = records[8]
    assert isinstance(rule.value, str)
    value = rule.value.replace("Action=Allow|", "Action=Allow|Future=one|") + "Future=two|"
    result = from_registry_records(records[:8] + [replace(rule, value=value)] + records[9:])
    unknown = result.policy.rules[0].unknown_tokens
    assert unknown == (UnknownFirewallToken(1, "Future=one"), UnknownFirewallToken(8, "Future=two"))
    with pytest.raises(FirewallValidationError) as error:
        to_registry_settings(result.policy)
    assert error.value.issues[0].code == "firewall_unknown_tokens"
    assert result.policy.validate() == error.value.issues


def test_unrecognised_records_and_wrong_side_survive() -> None:
    unknown = PolRecord(FIREWALL_KEY + r"\Unmeasured", "Future", "REG_SZ", "untouched")
    unrelated = PolRecord(r"SOFTWARE\Policies\Studio", "Test", "REG_DWORD", 123)
    wrong_side = RegistrySetting(
        "synthetic", "user", "HKCU", FIREWALL_KEY, "PolicyVersion", "REG_DWORD", 545
    )
    result = from_registry_records([unknown, unrelated, wrong_side] + parse(native_bytes()))
    assert result.policy == expected_policy()
    assert result.unrecognised_records == (unknown, unrelated, wrong_side)


@pytest.mark.parametrize(
    ("change", "code"),
    [
        ({"protocol": 99}, "unmeasured_protocol"),
        ({"protocol": True}, "unmeasured_protocol"),
        ({"profiles": ("public",)}, "unmeasured_profiles"),
        ({"profiles": ("private", "domain")}, "unmeasured_profiles"),
        ({"local_port": "80-90"}, "unmeasured_local_port"),
        ({"local_port": "80,443"}, "unmeasured_local_port"),
        ({"local_port": "IPHTTPS"}, "unmeasured_local_port"),
        ({"local_port": "0"}, "unmeasured_local_port"),
        ({"local_port": "65536"}, "unmeasured_local_port"),
        ({"protocol": 1}, "port_protocol"),
        ({"protocol": 17, "local_port": "RPC"}, "keyword_protocol"),
        ({"remote_port": 65536}, "invalid_remote_port"),
        ({"remote_port": 443}, "unmeasured_token_combination"),
        ({"remote_port_range": (90, 80)}, "invalid_remote_range"),
        ({"icmp4": "3:0"}, "unmeasured_icmp"),
        ({"local_address": "2001:db8::1"}, "unmeasured_address"),
        ({"remote_addresses": ("DNS",)}, "unmeasured_address"),
        ({"remote_addresses": ("192.0.2.7",)}, "unmeasured_address"),
        ({"remote_addresses": ("192.0.2.0/24", "198.51.100.0/24")}, "unmeasured_address_list"),
        ({"remote_addresses": ("LocalSubnet", "192.0.2.0/24")}, "unmeasured_address_list"),
        ({"interface_type": "Wireless"}, "unmeasured_interface"),
        ({"edge_traversal": False}, "unmeasured_edge"),
        ({"name": "injected|Action=Allow"}, "invalid_text"),
        ({"name": ""}, "invalid_text"),
        ({"rule_id": r"bad\identity"}, "invalid_rule_id"),
        ({"program": "bad\0path"}, "invalid_text"),
        ({"action": "bypass"}, "unmeasured_security"),
        ({"security": "Authenticate"}, "unmeasured_security"),
    ],
)
def test_refuse_unmeasured_rule_shapes(change: dict[str, object], code: str) -> None:
    rule = replace(expected_policy().rules[0], **change)
    with pytest.raises(FirewallValidationError) as error:
        to_registry_settings(FirewallPolicy(policy_version=545, rules=(rule,)))
    assert error.value.issues[0].code == "firewall_" + code
    assert rule.validate() == error.value.issues


@pytest.mark.parametrize(
    ("settings", "code"),
    [
        (FirewallProfileSettings(enabled=False), "unmeasured_profile_boolean"),
        (FirewallProfileSettings(disable_notifications=False), "unmeasured_profile_boolean"),
        (FirewallProfileSettings(default_inbound_action="allow"), "unmeasured_profile_action"),
        (FirewallProfileSettings(default_outbound_action="block"), "unmeasured_profile_action"),
        (FirewallProfileSettings(log_file_size_kb=4096), "unmeasured_log_size"),
        (FirewallProfileSettings(log_file_path=""), "invalid_text"),
    ],
)
def test_refuse_unmeasured_profile_values(settings: FirewallProfileSettings, code: str) -> None:
    with pytest.raises(FirewallValidationError) as error:
        to_registry_settings(FirewallPolicy(policy_version=545, domain=settings))
    assert error.value.issues[0].code == "firewall_" + code


def test_public_configuration_version_and_duplicates_refused() -> None:
    for policy, code in (
        (FirewallPolicy(policy_version=546), "unmeasured_policy_version"),
        (replace(expected_policy(), policy_version=None), "missing_policy_version"),
        (
            FirewallPolicy(policy_version=545, public=FirewallProfileSettings(enabled=True)),
            "unmeasured_public_settings",
        ),
        (replace(expected_policy(), rules=(expected_policy().rules[0],) * 2), "duplicate_rule"),
    ):
        with pytest.raises(FirewallValidationError) as error:
            to_registry_settings(policy)
        assert error.value.issues[0].code == "firewall_" + code


@pytest.mark.parametrize(
    ("old", "new", "code"),
    [
        ("v2.33", "v2.34", "unmeasured_rule_version"),
        ("Action=Allow", "Action=Unknown", "unmeasured_action"),
        ("Active=TRUE", "Active=1", "invalid_active"),
        ("Dir=In", "Dir=Sideways", "unmeasured_direction"),
        ("Protocol=6", "Protocol=7", "unmeasured_protocol"),
        ("Protocol=6", "Protocol=TCP", "invalid_number"),
        ("LPort=65001", "LPort=", "malformed_token"),
        ("LPort=65001", "LPort=65001|LPort=65002", "duplicate_token"),
        ("Name=StudioFwProbe in tcp allow|", "", "missing_rule_token"),
        ("Profile=Domain", "Profile=Public", "unmeasured_profiles"),
        ("Protocol=6|Profile=Domain", "Profile=Domain|Protocol=6", "unmeasured_token_form"),
    ],
)
def test_parser_refuses_unmeasured_known_wire(old: str, new: str, code: str) -> None:
    records = parse(native_bytes())
    rule = records[8]
    assert isinstance(rule.value, str)
    with pytest.raises(FirewallValidationError) as error:
        from_registry_records(
            records[:8] + [replace(rule, value=rule.value.replace(old, new))] + records[9:]
        )
    assert error.value.issues[0].code == "firewall_" + code


@pytest.mark.parametrize(
    ("index", "change", "code"),
    [
        (0, {"value": 546}, "unmeasured_policy_version"),
        (1, {"registry_type": "REG_SZ", "value": "1"}, "invalid_profile_type"),
        (1, {"value": 2}, "invalid_profile_boolean"),
        (1, {"value": 0}, "unmeasured_profile_boolean"),
        (2, {"value": 0}, "unmeasured_profile_action"),
        (8, {"registry_type": "REG_EXPAND_SZ"}, "invalid_rule_type"),
        (8, {"action": "delete"}, "unmeasured_record_action"),
    ],
)
def test_parser_refuses_invalid_registry_values(
    index: int, change: dict[str, object], code: str
) -> None:
    records = parse(native_bytes())
    records[index] = replace(records[index], **change)
    with pytest.raises(FirewallValidationError) as error:
        from_registry_records(records)
    assert error.value.issues[0].code == "firewall_" + code


def test_duplicate_case_insensitive_record_refused_and_models_frozen() -> None:
    records = parse(native_bytes())
    with pytest.raises(FirewallValidationError, match="firewall_duplicate_record"):
        from_registry_records(records + [replace(records[0], value_name="policyversion")])
    with pytest.raises(FrozenInstanceError):
        expected_policy().rules[0].name = "changed"  # type: ignore[misc]


def test_capture_provenance_hashes_extensions_and_normalizations() -> None:
    provenance = json.loads((FIXTURE / "provenance.json").read_text())
    capture = json.loads((FIXTURE / "capture.json").read_text(encoding="utf-8-sig"))
    assert provenance["capture_date"] == "2026-10-08"
    assert (
        provenance["capture_script_sha256"]
        == hashlib.sha256((ROOT / provenance["capture_script"]).read_bytes()).hexdigest()
    )
    assert provenance["registry_pol"]["sha256"] == hashlib.sha256(native_bytes()).hexdigest()
    assert base64.b64decode(capture["registry_pol_base64"]) == native_bytes()
    assert next(FIXTURE.rglob("registry.pol")).read_bytes() == native_bytes()
    assert capture["authoring_errors"] == [] and capture["error"] is None
    assert capture["cleanup_state_restored"] is True
    assert (
        capture["persistent_store_matches_before"] == capture["persistent_store_matches_after"] == 0
    )
    assert capture["ad_attributes"]["gPCMachineExtensionNames"] == (
        "[{35378EAC-683F-11D2-A89A-00C04FBBCFA2}" + FIREWALL_TOOL_GUID + "]"
    )
    assert capture["ad_attributes"]["gPCUserExtensionNames"] == ""
    assert capture["rules_readback"][2]["local_port"] == "RPC"
    assert expected_policy().rules[2].local_port is None
    assert "icmpv4-port-filter-rpc" in {f["name"] for f in provenance["normalizations"]}
    for entry in provenance["files"]:
        assert (
            hashlib.sha256((FIXTURE / entry["relative_path"]).read_bytes()).hexdigest()
            == entry["sanitized_sha256"]
        )
    for path in FIXTURE.rglob("*.xml"):
        ET.fromstring(path.read_bytes())


def test_sanitizer_reproduces_fixture_without_raw_inbox(tmp_path: Path) -> None:
    # Idempotent synthetic input exercises binary preservation, XML validity,
    # stable hashing and the no-overwrite guard without depending on raw data.
    module = runpy.run_path(str(ROOT / "scripts/plan-033/sanitize-firewall-fixtures.py"))
    module["sanitize"](FIXTURE, tmp_path / "copy")
    assert (tmp_path / "copy/Registry.pol").read_bytes() == native_bytes()
    copied = json.loads((tmp_path / "copy/capture.json").read_text(encoding="utf-8-sig"))
    assert copied["target_name"] == "zz-studio-firewall-native"
    with pytest.raises(ValueError, match="must not already exist"):
        module["sanitize"](FIXTURE, tmp_path / "copy")


def test_sanitizer_redacts_synthetic_estate_identities(tmp_path: Path) -> None:
    import shutil

    source = tmp_path / "raw"
    shutil.copytree(FIXTURE, source)
    replacements = (
        ("zz-studio-dc.studio.example", "zz-capture-dc.lab.example"),
        ("studio.example", "lab.example"),
        ("STUDIO", "CAPTURELAB"),
        ("11111111-1111-4111-8111-111111111111", "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa"),
        ("22222222-2222-4222-8222-222222222222", "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb"),
        ("33333333-3333-4333-8333-333333333333", "cccccccc-cccc-4ccc-8ccc-cccccccccccc"),
        ("S-1-5-21-0000000000-0000000000-0000000000", "S-1-5-21-1010101010-2020202020-3030303030"),
        ("zz-studio-firewall-native", "zz-capture-gpo"),
        ("01 00 04 80 00 00 00 00", "AA BB CC DD"),
    )
    for path in source.rglob("*"):
        if not path.is_file() or path.suffix not in (".xml", ".json"):
            continue
        raw = path.read_bytes()
        encoding = "utf-16" if raw.startswith((b"\xff\xfe", b"\xfe\xff")) else "utf-8-sig"
        text = raw.decode(encoding)
        for old, new in replacements:
            text = text.replace(old, new)
        path.write_bytes(text.encode(encoding))
    backup = source / "backup/{33333333-3333-4333-8333-333333333333}"
    backup.rename(source / "backup/{cccccccc-cccc-4ccc-8ccc-cccccccccccc}")
    module = runpy.run_path(str(ROOT / "scripts/plan-033/sanitize-firewall-fixtures.py"))
    destination = tmp_path / "sanitized"
    module["sanitize"](source, destination)
    assert (destination / "Registry.pol").read_bytes() == native_bytes()
    assert next(destination.rglob("registry.pol")).read_bytes() == native_bytes()
    for path in destination.rglob("*"):
        if not path.is_file() or path.suffix not in (".xml", ".json"):
            continue
        raw = path.read_bytes()
        text = raw.decode("utf-16" if raw.startswith((b"\xff\xfe", b"\xfe\xff")) else "utf-8-sig")
        for _, synthetic_original in replacements:
            assert synthetic_original.casefold() not in text.casefold()
    provenance = json.loads((destination / "provenance.json").read_text())
    transformations = {t for entry in provenance["files"] for t in entry["transformations_applied"]}
    assert transformations == {
        "replace-domain-host-account-gpo-and-backup-identities",
        "replace-domain-sid-prefix",
        "replace-security-descriptor-hex-with-placeholder",
    }


def test_sanitizer_refuses_identity_bearing_pol(tmp_path: Path) -> None:
    import shutil

    source = tmp_path / "raw"
    shutil.copytree(FIXTURE, source)
    capture_path = source / "capture.json"
    capture = json.loads(capture_path.read_text(encoding="utf-8-sig"))
    # A synthetic domain SID in binary content must trigger the audit before
    # copying anything. No raw capture or actual identity is used in this test.
    capture["registry_pol_base64"] = base64.b64encode(
        native_bytes() + "S-1-5-21-1010101010-2020202020-3030303030".encode("utf-16le")
    ).decode("ascii")
    capture_path.write_text(json.dumps(capture))
    module = runpy.run_path(str(ROOT / "scripts/plan-033/sanitize-firewall-fixtures.py"))
    with pytest.raises(ValueError, match="contains estate identifiers"):
        module["sanitize"](source, tmp_path / "sanitized")
    assert not (tmp_path / "sanitized").exists()
