"""Build reviewable, deterministic publication artifacts."""

from __future__ import annotations

import io
import json
import zipfile
from dataclasses import asdict

from .canonical import semantic_dict, semantic_hash
from .model import GPO, RegistrySetting
from .registry_pol import serialize
from .validation import validate_gpo


def _ps_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def _ps_value(setting: RegistrySetting) -> str:
    if isinstance(setting.value, int):
        return str(setting.value)
    if isinstance(setting.value, list):
        return "@(" + ", ".join(_ps_quote(item) for item in setting.value) + ")"
    if setting.registry_type == "REG_BINARY":
        clean = setting.value.replace(" ", "")
        return (
            "[byte[]](" + ",".join(f"0x{clean[i : i + 2]}" for i in range(0, len(clean), 2)) + ")"
        )
    return _ps_quote(setting.value)


def powershell_plan(gpo: GPO) -> str:
    """Generate an idempotent, human-reviewable GroupPolicy module plan."""
    lines = [
        "# Generated by GPO Studio. Review before running with delegated GPO rights.",
        "# This plan intentionally does not run from the web application.",
        "#Requires -Modules GroupPolicy",
        "[CmdletBinding(SupportsShouldProcess=$true)]",
        "param()",
        "$ErrorActionPreference = 'Stop'",
        f"$gpo = Get-GPO -Guid {_ps_quote(gpo.guid)} -ErrorAction SilentlyContinue",
        "if (-not $gpo) {",
        f"    $gpo = Get-GPO -Name {_ps_quote(gpo.name)} -ErrorAction SilentlyContinue",
        "}",
        "if (-not $gpo) {",
        f"    $gpo = New-GPO -Name {_ps_quote(gpo.name)} -Comment {_ps_quote(gpo.description)}",
        "}",
        "elseif ($gpo.DisplayName -ne " + _ps_quote(gpo.name) + ") {",
        f"    Rename-GPO -Guid $gpo.Id -TargetName {_ps_quote(gpo.name)} | Out-Null",
        "}",
        "",
    ]
    for setting in gpo.settings:
        key = f"{setting.hive}\\{setting.key}"
        if setting.action == "delete":
            lines.append(
                "Remove-GPRegistryValue -Guid $gpo.Id"
                f" -Key {_ps_quote(key)} -ValueName {_ps_quote(setting.value_name)}"
                " -ErrorAction SilentlyContinue"
            )
        else:
            type_name = setting.registry_type.removeprefix("REG_").replace("_SZ", "String").title()
            type_map = {
                "REG_SZ": "String",
                "REG_EXPAND_SZ": "ExpandString",
                "REG_BINARY": "Binary",
                "REG_DWORD": "DWord",
                "REG_MULTI_SZ": "MultiString",
                "REG_QWORD": "QWord",
            }
            lines.append(
                "Set-GPRegistryValue -Guid $gpo.Id"
                f" -Key {_ps_quote(key)} -ValueName {_ps_quote(setting.value_name)}"
                f" -Type {type_map.get(setting.registry_type, type_name)}"
                f" -Value {_ps_value(setting)}"
            )
    if gpo.links:
        lines.extend(["", "# Link intent (New-GPLink updates an existing link when present)."])
    for link in gpo.links:
        target = _ps_quote(link.target)
        common = (
            f"-Guid $gpo.Id -Target {target}"
            f" -LinkEnabled {'Yes' if link.enabled else 'No'}"
            f" -Enforced {'Yes' if link.enforced else 'No'} -Order {link.order}"
        )
        lines.extend(
            [
                f"$existingLink = (Get-GPInheritance -Target {target}).GpoLinks |",
                "    Where-Object { $_.GpoId -eq $gpo.Id }",
                f"if ($existingLink) {{ Set-GPLink {common} | Out-Null }}",
                f"else {{ New-GPLink {common} | Out-Null }}",
            ]
        )
    lines.extend(
        [
            "",
            "# Side enablement is explicit in the draft.",
            "$gpo.GpoStatus = [Microsoft.GroupPolicy.GpoStatus]::"
            + (
                "AllSettingsEnabled"
                if gpo.computer_enabled and gpo.user_enabled
                else "UserSettingsDisabled"
                if gpo.computer_enabled
                else "ComputerSettingsDisabled"
                if gpo.user_enabled
                else "AllSettingsDisabled"
            ),
        ]
    )
    return "\n".join(lines) + "\n"


def export_bundle(gpo: GPO) -> bytes:
    """Return a deterministic ZIP containing manifest, PReg files, and plan."""
    issues = validate_gpo(gpo)
    manifest = {
        "schema_version": 2,
        "kind": "gpo-studio-publication-bundle",
        "gpo": gpo.to_dict(),
        "validation": [asdict(issue) for issue in issues],
        "semantic_sha256": semantic_hash(gpo),
        "canonical_model": semantic_dict(gpo),
    }
    computer = [item for item in gpo.settings if item.side == "computer"]
    user = [item for item in gpo.settings if item.side == "user"]
    output = io.BytesIO()
    with zipfile.ZipFile(output, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        entries = {
            "manifest.json": json.dumps(manifest, indent=2, sort_keys=True).encode(),
            "apply.ps1": powershell_plan(gpo).encode("utf-8-sig"),
            "Machine/Registry.pol": serialize(computer),
            "User/Registry.pol": serialize(user),
        }
        for name, content in entries.items():
            info = zipfile.ZipInfo(name, date_time=(1980, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o600 << 16
            archive.writestr(info, content)
    return output.getvalue()
