"""Build reviewable, deterministic publication artifacts."""

from __future__ import annotations

import io
import json
import xml.etree.ElementTree as ET
import zipfile
from dataclasses import asdict

from .canonical import semantic_dict, semantic_hash
from .model import GPO, RegistrySetting
from .registry_pol import PolRecord, serialize
from .validation import validate_gpo

_GPMC_NS = "http://www.microsoft.com/GroupPolicy/Types"
_REGISTRY_CSE_GUID = "{35378EAC-683F-11D2-A89A-00C04FBBCFA2}"


def _ps_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def _ps_sanitize_comment(text: str) -> str:
    return text.replace("\r", " ").replace("\n", " ")


def _ps_value(setting: RegistrySetting) -> str:
    if isinstance(setting.value, int):
        return str(setting.value)
    if isinstance(setting.value, list):
        return "@(" + ", ".join(_ps_quote(item) for item in setting.value) + ")"
    if setting.registry_type == "REG_BINARY":
        clean = setting.value.replace(" ", "")
        return (
            "[byte[]](" + ",".join(f"0x{clean[i : i + 2]}" for i in range(0, len(clean), 2)) + ")"
        )
    return _ps_quote(setting.value)


def powershell_plan(gpo: GPO) -> str:
    """Generate an idempotent, human-reviewable GroupPolicy module plan."""
    lines = [
        "# Generated by GPO Studio. Review before running with delegated GPO rights.",
        "# This plan intentionally does not run from the web application.",
        "#Requires -Modules GroupPolicy",
        "[CmdletBinding(SupportsShouldProcess=$true)]",
        "param()",
        "$ErrorActionPreference = 'Stop'",
        f"$gpo = Get-GPO -Guid {_ps_quote(gpo.guid)} -ErrorAction SilentlyContinue",
        "if (-not $gpo) {",
        f"    $gpo = Get-GPO -Name {_ps_quote(gpo.name)} -ErrorAction SilentlyContinue",
        "}",
        "if (-not $gpo) {",
        f"    $gpo = New-GPO -Name {_ps_quote(gpo.name)} -Comment {_ps_quote(gpo.description)}",
        "}",
        "elseif ($gpo.DisplayName -ne " + _ps_quote(gpo.name) + ") {",
        f"    Rename-GPO -Guid $gpo.Id -TargetName {_ps_quote(gpo.name)} | Out-Null",
        "}",
        "",
    ]
    for setting in gpo.settings:
        key = f"{setting.hive}\\{setting.key}"
        if setting.action == "delete":
            lines.append(
                "Remove-GPRegistryValue -Guid $gpo.Id"
                f" -Key {_ps_quote(key)} -ValueName {_ps_quote(setting.value_name)}"
                " -ErrorAction SilentlyContinue"
            )
        else:
            type_map = {
                "REG_SZ": "String",
                "REG_EXPAND_SZ": "ExpandString",
                "REG_BINARY": "Binary",
                "REG_DWORD": "DWord",
                "REG_MULTI_SZ": "MultiString",
                "REG_QWORD": "QWord",
            }
            lines.append(
                "Set-GPRegistryValue -Guid $gpo.Id"
                f" -Key {_ps_quote(key)} -ValueName {_ps_quote(setting.value_name)}"
                f" -Type {type_map[setting.registry_type]}"
                f" -Value {_ps_value(setting)}"
            )
    if gpo.links:
        lines.extend(["", "# Link intent (New-GPLink updates an existing link when present)."])
    for link in gpo.links:
        target = _ps_quote(link.target)
        common = (
            f"-Guid $gpo.Id -Target {target}"
            f" -LinkEnabled {'Yes' if link.enabled else 'No'}"
            f" -Enforced {'Yes' if link.enforced else 'No'} -Order {link.order}"
        )
        lines.extend(
            [
                f"$existingLink = (Get-GPInheritance -Target {target}).GpoLinks |",
                "    Where-Object { $_.GpoId -eq $gpo.Id }",
                f"if ($existingLink) {{ Set-GPLink {common} | Out-Null }}",
                f"else {{ New-GPLink {common} | Out-Null }}",
            ]
        )
    if gpo.security_filters:
        lines.append("")
        lines.append("# Security filtering")
        for sf in sorted(gpo.security_filters, key=lambda s: s.principal.casefold()):
            perm = "GpoApply" if sf.permission == "apply" else "GpoRead"
            target_type_ps = sf.target_type.title()
            lines.append(
                f"Set-GPPermission -Guid $gpo.Id -PermissionLevel {perm}"
                f" -TargetName {_ps_quote(sf.principal)} -TargetType {target_type_ps} -Replace"
                " | Out-Null"
            )
    if gpo.wmi_filter is not None:
        wmi_name = _ps_sanitize_comment(gpo.wmi_filter.name)
        wmi_query = _ps_sanitize_comment(gpo.wmi_filter.query)
        lines.append("")
        lines.append(f"# WMI filter: {wmi_name} ({wmi_query})")
        lines.append(
            f"# Assign WMI filter '{wmi_name}' to this GPO via GPMC or the"
            f" GPMC COM API (domain: {gpo.domain})."
        )
    status_value: str
    if gpo.computer_enabled and gpo.user_enabled:
        status_value = "AllSettingsEnabled"
    elif gpo.computer_enabled:
        status_value = "UserSettingsDisabled"
    elif gpo.user_enabled:
        status_value = "ComputerSettingsDisabled"
    else:
        status_value = "AllSettingsDisabled"

    lines.extend(
        [
            "",
            "# Side enablement is explicit in the draft.",
            f"Set-GPO -Guid $gpo.Id -Status {status_value} | Out-Null",
        ]
    )
    return "\n".join(lines) + "\n"


def export_bundle(gpo: GPO) -> bytes:
    """Return a deterministic ZIP containing manifest, PReg files, and plan."""
    issues = validate_gpo(gpo)
    manifest = {
        "schema_version": 2,
        "kind": "gpo-studio-publication-bundle",
        "gpo": gpo.to_dict(),
        "validation": [asdict(issue) for issue in issues],
        "semantic_sha256": semantic_hash(gpo),
        "canonical_model": semantic_dict(gpo),
    }
    computer = [item for item in gpo.settings if item.side == "computer"]
    user = [item for item in gpo.settings if item.side == "user"]
    output = io.BytesIO()
    with zipfile.ZipFile(output, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        entries = {
            "manifest.json": json.dumps(manifest, indent=2, sort_keys=True).encode(),
            "apply.ps1": powershell_plan(gpo).encode("utf-8-sig"),
            "Machine/Registry.pol": serialize(computer),
            "User/Registry.pol": serialize(user),
        }
        for name, content in entries.items():
            info = zipfile.ZipInfo(name, date_time=(1980, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o600 << 16
            archive.writestr(info, content)
    return output.getvalue()


def _gpmc_preg_bytes(settings: list[RegistrySetting]) -> bytes:
    records = [
        PolRecord(
            key=f"{s.hive}\\{s.key}",
            value_name=s.value_name,
            registry_type=s.registry_type,
            value=s.value,
            action=s.action,
        )
        for s in settings
    ]
    return serialize(records)


def _xml_to_bytes(root: ET.Element) -> bytes:
    ET.register_namespace("", _GPMC_NS)
    xml_str = ET.tostring(root, encoding="unicode")
    return b'<?xml version="1.0" encoding="utf-8"?>\n' + xml_str.encode("utf-8")


def _build_manifest_xml(gpo: GPO) -> bytes:
    root = ET.Element(f"{{{_GPMC_NS}}}BackupInstances")
    inst = ET.SubElement(root, f"{{{_GPMC_NS}}}BackupInstance")
    ET.SubElement(inst, f"{{{_GPMC_NS}}}BackupTime").text = "1980-01-01T00:00:00"
    ET.SubElement(inst, f"{{{_GPMC_NS}}}ID").text = f"{{{gpo.guid}}}"
    gpo_elem = ET.SubElement(inst, f"{{{_GPMC_NS}}}GPO")
    ET.SubElement(gpo_elem, f"{{{_GPMC_NS}}}Identifier").text = gpo.guid
    ET.SubElement(gpo_elem, f"{{{_GPMC_NS}}}DisplayName").text = gpo.name
    ET.SubElement(gpo_elem, f"{{{_GPMC_NS}}}Domain").text = gpo.domain
    has_computer = any(s.side == "computer" for s in gpo.settings)
    has_user = any(s.side == "user" for s in gpo.settings)
    if has_computer:
        ET.SubElement(gpo_elem, f"{{{_GPMC_NS}}}MachineExtensionGuids").text = _REGISTRY_CSE_GUID
    if has_user:
        ET.SubElement(gpo_elem, f"{{{_GPMC_NS}}}UserExtensionGuids").text = _REGISTRY_CSE_GUID
    _append_security_filters(gpo_elem, gpo)
    if gpo.wmi_filter is not None:
        wmi_elem = ET.SubElement(gpo_elem, f"{{{_GPMC_NS}}}WmiFilter")
        wmi_elem.set("name", gpo.wmi_filter.name)
        wmi_elem.set("query", gpo.wmi_filter.query)
        wmi_elem.set("language", gpo.wmi_filter.language)
        wmi_elem.set("description", gpo.wmi_filter.description)
    return _xml_to_bytes(root)


def _append_security_filters(parent: ET.Element, gpo: GPO) -> None:
    if not gpo.security_filters:
        return
    sf_elem = ET.SubElement(parent, f"{{{_GPMC_NS}}}SecurityFilters")
    for sf in sorted(gpo.security_filters, key=lambda s: s.principal.casefold()):
        child = ET.SubElement(sf_elem, f"{{{_GPMC_NS}}}SecurityFilter")
        child.set("principal", sf.principal)
        child.set("permission", "GpoApply" if sf.permission == "apply" else "GpoRead")
        child.set("inheritable", "true" if sf.inheritable else "false")
        child.set("target_type", sf.target_type)


def _build_bkup_info_xml(gpo: GPO) -> bytes:
    root = ET.Element(f"{{{_GPMC_NS}}}BackupInfo")
    ET.SubElement(root, f"{{{_GPMC_NS}}}BackupTime").text = "1980-01-01T00:00:00"
    ET.SubElement(root, f"{{{_GPMC_NS}}}ID").text = f"{{{gpo.guid}}}"
    ET.SubElement(root, f"{{{_GPMC_NS}}}BackupType").text = "GPO"
    gpo_elem = ET.SubElement(root, f"{{{_GPMC_NS}}}GPO")
    ET.SubElement(gpo_elem, f"{{{_GPMC_NS}}}Identifier").text = gpo.guid
    ET.SubElement(gpo_elem, f"{{{_GPMC_NS}}}DisplayName").text = gpo.name
    ET.SubElement(gpo_elem, f"{{{_GPMC_NS}}}Domain").text = gpo.domain
    return _xml_to_bytes(root)


def _build_gpreport_xml(gpo: GPO) -> bytes:
    root = ET.Element(f"{{{_GPMC_NS}}}GroupPolicyReport")
    gpo_elem = ET.SubElement(root, f"{{{_GPMC_NS}}}GPO")
    ET.SubElement(gpo_elem, f"{{{_GPMC_NS}}}Identifier").text = gpo.guid
    ET.SubElement(gpo_elem, f"{{{_GPMC_NS}}}DisplayName").text = gpo.name
    _append_security_filters(gpo_elem, gpo)
    if gpo.wmi_filter is not None:
        wmi_elem = ET.SubElement(gpo_elem, f"{{{_GPMC_NS}}}WmiFilter")
        wmi_elem.set("name", gpo.wmi_filter.name)
        wmi_elem.set("query", gpo.wmi_filter.query)
        wmi_elem.set("language", gpo.wmi_filter.language)
        wmi_elem.set("description", gpo.wmi_filter.description)
    return _xml_to_bytes(root)


def _build_dc_xml() -> bytes:
    root = ET.Element(f"{{{_GPMC_NS}}}DomainController")
    ET.SubElement(root, f"{{{_GPMC_NS}}}Name").text = "UNKNOWN"
    return _xml_to_bytes(root)


def gpmc_backup_bundle(gpo: GPO) -> bytes:
    """Return a deterministic GPMC backup ZIP for a registry-only GPO."""
    computer = [item for item in gpo.settings if item.side == "computer"]
    user = [item for item in gpo.settings if item.side == "user"]
    output = io.BytesIO()
    with zipfile.ZipFile(output, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        entries: dict[str, bytes] = {
            "manifest.xml": _build_manifest_xml(gpo),
            "bkupInfo.xml": _build_bkup_info_xml(gpo),
            f"{gpo.guid}/Machine/Registry.pol": _gpmc_preg_bytes(computer),
            f"{gpo.guid}/User/Registry.pol": _gpmc_preg_bytes(user),
            f"{gpo.guid}/gpreport.xml": _build_gpreport_xml(gpo),
            f"{gpo.guid}/DomainController.xml": _build_dc_xml(),
        }
        for name in sorted(entries):
            info = zipfile.ZipInfo(name, date_time=(1980, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o600 << 16
            archive.writestr(info, entries[name])
    return output.getvalue()
