"""PowerShell plan validation for generated apply.ps1 artifacts.

Plan 017 WP-4: parse generated plans and reject unexpected command shapes,
injection attempts, and structural violations before execution.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Literal

_ALLOWED_CMDLETS: frozenset[str] = frozenset({
    "Get-GPO",
    "New-GPO",
    "Rename-GPO",
    "Set-GPRegistryValue",
    "Remove-GPRegistryValue",
    "New-GPLink",
    "Set-GPLink",
    "Get-GPInheritance",
    "Get-GPPermission",
    "Set-GPPermission",
    "Where-Object",
    "Out-Null",
})

_DANGEROUS_TOKENS: frozenset[str] = frozenset({
    "iex", "irm", "iwr", "ri", "ni", "start",
    "Invoke-Expression",
})

_CMDLET_RE = re.compile(r"(?<![A-Za-z-])([A-Z][a-z]+-[A-Z][A-Za-z]+)")


@dataclass(frozen=True, slots=True)
class PlanValidationIssue:
    severity: Literal["error", "warning"]
    code: str
    message: str
    line: int


@dataclass(frozen=True, slots=True)
class PlanValidationResult:
    valid: bool
    issues: tuple[PlanValidationIssue, ...] = ()

    @property
    def errors(self) -> tuple[PlanValidationIssue, ...]:
        return tuple(i for i in self.issues if i.severity == "error")

    @property
    def warnings(self) -> tuple[PlanValidationIssue, ...]:
        return tuple(i for i in self.issues if i.severity == "warning")


def _strip_single_quoted_tracked(
    line: str, in_string: bool
) -> tuple[str, bool]:
    """Strip single-quoted string content from a line.

    Returns (code_outside_strings, still_in_string_at_eol). When
    *in_string* is True on entry, the line begins inside an open string
    (multi-line continuation) and characters are suppressed until a
    closing quote is found.
    """
    result: list[str] = []
    i = 0
    while i < len(line):
        ch = line[i]
        if ch == "'" and not in_string:
            in_string = True
            i += 1
            continue
        if ch == "'" and in_string:
            if i + 1 < len(line) and line[i + 1] == "'":
                i += 2
                continue
            in_string = False
            i += 1
            continue
        if not in_string:
            result.append(ch)
        i += 1
    return "".join(result), in_string


def _is_comment_line(line: str) -> bool:
    stripped = line.lstrip()
    return stripped.startswith("#")


def validate_plan(plan_text: str) -> PlanValidationResult:
    issues: list[PlanValidationIssue] = []
    lines = plan_text.splitlines()

    if not lines:
        return PlanValidationResult(
            valid=False,
            issues=(PlanValidationIssue("error", "empty_plan", "Plan is empty", 1),),
        )

    has_header = any(
        "Generated by GPO Studio" in line for line in lines[:5]
    )
    if not has_header:
        issues.append(PlanValidationIssue(
            "error", "missing_header",
            "Plan must start with the GPO Studio header comment", 1,
        ))

    has_requires = any("#Requires -Modules GroupPolicy" in line for line in lines)
    if not has_requires:
        issues.append(PlanValidationIssue(
            "error", "missing_requires",
            "Plan must contain '#Requires -Modules GroupPolicy'", 1,
        ))

    has_cmdlet_binding = any("[CmdletBinding" in line for line in lines)
    if not has_cmdlet_binding:
        issues.append(PlanValidationIssue(
            "error", "missing_cmdlet_binding",
            "Plan must contain [CmdletBinding(SupportsShouldProcess=$true)]", 1,
        ))

    has_gpo_status = any("$gpo.GpoStatus" in line for line in lines)
    if not has_gpo_status:
        issues.append(PlanValidationIssue(
            "error", "missing_gpo_status",
            "Plan must end with $gpo.GpoStatus assignment", 1,
        ))

    gpo_assigned = False
    in_string = False
    for i, line in enumerate(lines, 1):
        stripped = line.strip()
        if not stripped or _is_comment_line(line):
            continue

        code, in_string = _strip_single_quoted_tracked(line, in_string)

        if not code:
            continue

        if "`" in code:
            issues.append(PlanValidationIssue(
                "error", "backtick_injection",
                f"Backtick character found outside string (line {i})", i,
            ))

        for token in _DANGEROUS_TOKENS:
            pattern = r"(?<![A-Za-z])" + re.escape(token) + r"(?![A-Za-z])"
            if re.search(pattern, code):
                issues.append(PlanValidationIssue(
                    "error", "dangerous_token",
                    f"Dangerous token '{token}' on line {i}", i,
                ))

        if (
            "$gpo " in code or "$gpo=" in code.replace(" ", "") or "$gpo =" in code
        ) and ("Get-GPO" in code or "New-GPO" in code):
            gpo_assigned = True

        if "$gpo." in code and not gpo_assigned and "$gpo.GpoStatus" in code:
            issues.append(PlanValidationIssue(
                "error", "variable_before_assignment",
                f"$gpo used before assignment (line {i})", i,
            ))

        for match in _CMDLET_RE.finditer(code):
            cmdlet = match.group(1)
            if cmdlet not in _ALLOWED_CMDLETS:
                issues.append(PlanValidationIssue(
                    "error", "disallowed_cmdlet",
                    f"Disallowed cmdlet '{cmdlet}' on line {i}", i,
                ))

        if ";" in code:
            issues.append(PlanValidationIssue(
                "error", "semicolon_injection",
                f"Semicolon chaining detected on line {i}", i,
            ))

        if "|" in code:
            code_stripped = code.rstrip()
            is_trailing_pipe = code_stripped.endswith("|")
            known_pipe_patterns = [
                "Where-Object",
                "Out-Null",
            ]
            if not is_trailing_pipe and not any(p in code for p in known_pipe_patterns):
                issues.append(PlanValidationIssue(
                    "error", "pipe_injection",
                    f"Unexpected pipe on line {i}", i,
                ))

    if not gpo_assigned and has_gpo_status:
        issues.append(PlanValidationIssue(
            "error", "gpo_never_assigned",
            "$gpo.GpoStatus is used but $gpo is never assigned via Get-GPO/New-GPO", 1,
        ))

    errors = [i for i in issues if i.severity == "error"]
    return PlanValidationResult(
        valid=len(errors) == 0,
        issues=tuple(issues),
    )
